import {
  Search,
  ArrowDownToLine,
  ShieldCheck,
  Check,
  Target,
  ChevronDown,
  ChevronRight,
  User,
  Square,
  Play,
  RotateCcw,
  ShieldQuestion,
  X,
  ArrowRight,
  Loader2,
  CircleAlert,
  Workflow,
  PanelLeftClose,
  PanelLeftOpen,
  LayoutList,
  Inbox,
  RotateCw,
  CreditCard,
  Mail,
  ScrollText,
  type LucideIcon,
} from "lucide-react";
import type { Activity } from "../loop/activities.js";

export {
  Search,
  ArrowDownToLine,
  ShieldCheck,
  Check,
  Target,
  ChevronDown,
  ChevronRight,
  User,
  Square,
  Play,
  RotateCcw,
  ShieldQuestion,
  X,
  ArrowRight,
  Loader2,
  CircleAlert,
  Workflow,
  PanelLeftClose,
  PanelLeftOpen,
  LayoutList,
  Inbox,
  RotateCw,
  CreditCard,
  Mail,
  ScrollText,
};

export const ACTIVITY_ICON: Record<Activity["kind"], LucideIcon> = {
  investigate: Search,
  propose: ArrowDownToLine,
  gate: ShieldCheck,
  execute: Check,
  nudge: Mail,
  outcome: Target,
};
